name: PR Sanity Check

on: 
  pull_request:
    types: [opened]
  # https://github.com/mshick/add-pr-comment/issues/25
  pull_request_target:
    types: [opened]

jobs:
  comment:
    name: Add link comment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            You can check this code at CodeSandbox with the link
            https://githubbox.com/${{ github.repository }}/tree/${{ github.head_ref }}

  lint:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
  
       - name: Install Packages
         run: |
           npm install
           echo "Dependencies installed"
  
       - name: Lint check
         run: |
           npm run lint
  
       - name: Lint check
         run: |
           npm run test
